"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Check, CheckCircle2, Lightbulb, MessageSquare, Pencil, Plus, Search, Send, ThumbsUp, Trash2 } from "lucide-react";
import { api } from "@/lib/client";
import type { AgentSummary } from "@/lib/contracts";
import { ideaStates, type CommunityReply, type IdeaState, type TopicDetail, type TopicView } from "@/lib/community-contracts";
import { useLanguage } from "../LanguageProvider";
import { useMarketplace, useResource } from "../MarketplaceProvider";
import { BusyIcon, EmptyState, ErrorBox, Field, Loading, Modal, useText } from "../ui";
import { CommunityMeta, CommunityRules, Contributor, FollowButton, ReportButton, TopicComposer, useCommunityAction, type CommunityAccess } from "./shared";

export function ideaStateLabel(state: IdeaState, tr: (ro: string, en: string) => string) {
  return ({ proposed: tr("Propus", "Proposed"), "in-progress": tr("În lucru", "In progress"), available: tr("Disponibil", "Available"), declined: tr("Neplanificat", "Not planned") })[state];
}
export function TopicRows({ topics }: { topics: TopicView[] }) {
  const tr = useText();
  return <div className="community-list">{topics.map(topic => <article className="community-row" key={topic.id}>
    <div className="community-row-icon">{topic.kind === "idea" ? <Lightbulb size={23}/> : topic.acceptedReplyId ? <CheckCircle2 size={23}/> : <MessageSquare size={23}/>}</div>
    <div className="community-row-body"><div className="community-row-title"><h2><Link href={`/community/topics/${topic.id}`}>{topic.title}</Link></h2>{topic.kind === "idea" && <span className="community-state" data-state={topic.state}>{ideaStateLabel(topic.state, tr)}</span>}{topic.acceptedReplyId && <span className="community-state" data-state="available">{tr("Rezolvat", "Answered")}</span>}{topic.hidden && <span className="community-state">{tr("Ascuns", "Hidden")}</span>}</div><p className="community-excerpt">{topic.body}</p><CommunityMeta authorId={topic.authorId} authorName={topic.authorName} date={topic.updatedAt} audience={topic.audience}/></div>
    <div className="community-counts"><span><MessageSquare size={14}/> {topic.replyCount}</span>{topic.kind === "idea" && <span><ThumbsUp size={14}/> {topic.voteCount}</span>}</div>
  </article>)}</div>;
}
export function TopicList({ kind, agentId, allowGuests = true }: { kind: "discussion" | "idea"; agentId?: string; allowGuests?: boolean }) {
  const tr = useText(); const router = useRouter(); const { data: bootstrap } = useMarketplace();
  const policy = useResource<CommunityAccess>("community/policy");
  const [query, setQuery] = useState(""); const [mine, setMine] = useState(false); const [status, setStatus] = useState(""); const [sort, setSort] = useState("recent"); const [compose, setCompose] = useState(false);
  const resource = useResource<TopicView[]>(`community/topics?kind=${kind}${agentId ? `&agentId=${encodeURIComponent(agentId)}` : ""}&mine=${mine}`);
  const topics = (resource.data ?? []).filter(topic => `${topic.title} ${topic.body} ${topic.authorName}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()) && (!status || (kind === "idea" ? topic.state === status : Boolean(topic.acceptedReplyId) === (status === "answered")))).sort((first, second) => sort === "votes" ? second.voteCount - first.voteCount : second.updatedAt.localeCompare(first.updatedAt));
  return <><div className="section-heading"><h2>{kind === "idea" ? tr("Idei de agenți", "Agent ideas") : tr("Întrebări și discuții", "Questions and discussions")}</h2>{policy.data?.canParticipate && (kind === "idea" || agentId) && <button className="button primary small" onClick={() => setCompose(true)}><Plus size={16}/>{kind === "idea" ? tr("Propune un agent", "Propose an agent") : tr("Adresează o întrebare", "Ask a question")}</button>}</div>
    <div className="community-filters"><div className="catalog-search compact"><Search size={17}/><input aria-label={tr("Caută în contribuții", "Search contributions")} value={query} onChange={event => setQuery(event.target.value)}/></div><select aria-label={tr("Stare contribuții", "Contribution status")} value={status} onChange={event => setStatus(event.target.value)}><option value="">{tr("Toate stările", "All statuses")}</option>{kind === "idea" ? ideaStates.map(state => <option key={state} value={state}>{ideaStateLabel(state, tr)}</option>) : <><option value="open">{tr("Fără răspuns acceptat", "Unanswered")}</option><option value="answered">{tr("Rezolvat", "Answered")}</option></>}</select>{kind === "idea" && <select aria-label={tr("Sortare idei", "Sort ideas")} value={sort} onChange={event => setSort(event.target.value)}><option value="recent">{tr("Activitate recentă", "Recent activity")}</option><option value="votes">{tr("Cele mai votate", "Most votes")}</option></select>}<label className="toggle-row"><input type="checkbox" checked={mine} onChange={event => setMine(event.target.checked)}/>{tr("Ale mele", "Mine")}</label></div>
    {resource.loading ? <Loading/> : resource.error ? <ErrorBox error={resource.error} retry={resource.reload}/> : topics.length ? <TopicRows topics={topics}/> : <EmptyState title={tr("Nicio contribuție găsită", "No contributions found")}>{kind === "discussion" && !agentId && <Link className="button" href="/">{tr("Explorează agenții", "Browse agents")}</Link>}</EmptyState>}
    <CommunityRules access={policy.data}/>
    {compose && <TopicComposer kind={kind} agentId={agentId} allowGuests={allowGuests} guest={bootstrap?.actor?.guest} close={() => setCompose(false)} saved={topic => { setCompose(false); resource.reload(); router.push(`/community/topics/${topic.id}`); }}/>}
  </>;
}

function IdeaProgress({ topic, refresh }: { topic: TopicView; refresh: () => void }) {
  const tr = useText(); const action = useCommunityAction();
  const [status, setStatus] = useState<IdeaState>(topic.state); const [note, setNote] = useState(""); const [agentId, setAgentId] = useState(topic.linkedAgentId);
  const agents = useResource<AgentSummary[]>("agents");
  return <section className="section-block"><h2>{tr("Responsabil și progres", "Owner and progress")}</h2><form className="form-stack" onSubmit={event => { event.preventDefault(); void action.run(async () => { await api(`community/topics/${topic.id}`, { method: "PATCH", body: { action: "progress", revision: topic.revision, state: status, note, linkedAgentId: agentId } }); refresh(); }); }}>
    {topic.assigneeId && <p><Contributor id={topic.assigneeId} name={topic.assigneeName}/></p>}
    {Boolean(action.error) && <ErrorBox error={action.error}/>}
    <div className="form-grid"><Field label={tr("Starea ideii", "Idea status")}><select value={status} onChange={event => setStatus(event.target.value as IdeaState)}>{ideaStates.map(value => <option key={value} value={value}>{ideaStateLabel(value, tr)}</option>)}</select></Field>{status === "available" && <Field label={tr("Agent publicat", "Published agent")} required><select required value={agentId} onChange={event => setAgentId(event.target.value)}><option value="">{tr("Selectează agentul", "Select agent")}</option>{agents.data?.map(agent => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></Field>}</div>
    <Field label={tr("Notă de progres", "Progress note")} required><textarea required minLength={5} maxLength={2000} rows={3} value={note} onChange={event => setNote(event.target.value)}/></Field>
    <div className="row-actions end"><button className="button primary" disabled={action.busy || note.trim().length < 5}>{action.busy ? <BusyIcon/> : <Check size={16}/>} {tr("Actualizează progresul", "Update progress")}</button></div>
  </form></section>;
}

export function CommunityDiscussion({ id }: { id: string }) {
  const tr = useText(); const router = useRouter(); const { locale } = useLanguage();
  const resource = useResource<TopicDetail>(`community/topics/${encodeURIComponent(id)}`); const policy = useResource<CommunityAccess>("community/policy"); const action = useCommunityAction();
  const [replyBody, setReplyBody] = useState(""); const [edit, setEdit] = useState(false); const [remove, setRemove] = useState<"topic" | CommunityReply | null>(null); const [editReply, setEditReply] = useState<CommunityReply | null>(null); const [replyEditBody, setReplyEditBody] = useState("");
  if (resource.loading) return <div className="page-width page-content"><Loading/></div>;
  if (resource.error || !resource.data) return <div className="page-width page-content"><ErrorBox error={resource.error ?? tr("Contribuție indisponibilă", "Contribution unavailable")} retry={resource.reload}/><Link href="/community">{tr("Înapoi la comunitate", "Back to community")}</Link></div>;
  const { topic, replies } = resource.data; const canParticipate = policy.data?.canParticipate && !topic.hidden;
  const mutate = (body: unknown) => action.run(async () => { await api(`community/topics/${id}`, { method: "PATCH", body }); resource.reload(); });
  return <div className="page-width page-content community-detail"><div className="breadcrumbs"><Link href="/community">{tr("Comunitate", "Community")}</Link><span>/</span><Link href={`/community?tab=${topic.kind === "idea" ? "ideas" : "discussions"}`}>{topic.kind === "idea" ? tr("Idei", "Ideas") : tr("Discuții", "Discussions")}</Link></div>
    <div className="community-detail-heading"><span className="eyebrow">{topic.kind === "idea" ? ideaStateLabel(topic.state, tr) : topic.acceptedReplyId ? tr("Rezolvat", "Answered") : tr("Întrebare deschisă", "Open question")}</span><h1>{topic.title}</h1><CommunityMeta authorId={topic.authorId} authorName={topic.authorName} date={topic.createdAt} audience={topic.audience}/></div>
    {topic.hidden && <div className="info-notice">{tr("Contribuția este ascunsă de moderatori și nu este afișată comunității.", "This contribution is hidden by moderators and is not shown to the community.")}</div>}
    {Boolean(action.error) && <ErrorBox error={action.error}/>}
    <div className="community-detail-tools">{!topic.hidden && <FollowButton target={{ kind: "topic", id }}/>} {topic.kind === "idea" && <button className="button" aria-pressed={topic.voted} disabled={!canParticipate || action.busy} onClick={() => void action.run(async () => { await api(`community/topics/${id}/vote`, { method: "PUT", body: { voted: !topic.voted } }); resource.reload(); })}><ThumbsUp size={16}/>{topic.voted ? tr("Retrage votul", "Remove vote") : tr("Votează", "Vote")} <strong>{topic.voteCount}</strong></button>}{topic.canEdit && canParticipate && <button className="icon-button" title={tr("Editează contribuția", "Edit contribution")} aria-label={tr("Editează contribuția", "Edit contribution")} onClick={() => setEdit(true)}><Pencil size={17}/></button>}{topic.canEdit && <button className="icon-button" title={tr("Șterge contribuția", "Remove contribution")} aria-label={tr("Șterge contribuția", "Remove contribution")} onClick={() => setRemove("topic")}><Trash2 size={17}/></button>}{!topic.hidden && <ReportButton kind="topic" id={id}/>}</div>
    <section className="community-original"><p className="prose">{topic.body}</p>{topic.agentId && <Link className="subtle-link" href={`/agents/${topic.agentId}?tab=community`}>{tr("Deschide agentul asociat", "Open related agent")}</Link>}</section>
    {topic.kind === "idea" && <section className="section-block"><div className="section-heading"><h2>{ideaStateLabel(topic.state, tr)}</h2>{topic.assigneeId && <Contributor id={topic.assigneeId} name={topic.assigneeName}/>}</div>{topic.decisionNote && <p className="prose">{topic.decisionNote}</p>}{topic.linkedAgentId && <Link className="button" href={`/agents/${topic.linkedAgentId}`}>{tr("Deschide agentul publicat", "Open published agent")}</Link>}</section>}
    {topic.canManage && canParticipate && <IdeaProgress key={topic.revision} topic={topic} refresh={resource.reload}/>}
    <section className="section-block"><h2>{tr("Răspunsuri", "Replies")} <span className="muted">{topic.replyCount}</span></h2><div className="community-replies">{replies.map(reply => <article className="community-reply" data-accepted={topic.acceptedReplyId === reply.id} key={reply.id}><div className="section-heading"><Contributor id={reply.authorId} name={reply.authorName}/><div className="row-actions">{topic.acceptedReplyId === reply.id && <span className="community-state" data-state="available"><CheckCircle2 size={15}/>{tr("Răspuns acceptat", "Accepted answer")}</span>}{reply.hidden && <span>{tr("Ascuns", "Hidden")}</span>}</div></div><p className="prose">{reply.body}</p><div className="community-reply-actions"><small className="muted">{new Date(reply.updatedAt).toLocaleString(locale)}</small><div className="row-actions">{topic.canAccept && canParticipate && !reply.hidden && <button className="button quiet small" disabled={action.busy} onClick={() => void mutate({ action: "accept", revision: topic.revision, replyId: topic.acceptedReplyId === reply.id ? "" : reply.id })}><Check size={15}/>{topic.acceptedReplyId === reply.id ? tr("Redeschide întrebarea", "Reopen question") : tr("Acceptă răspunsul", "Accept answer")}</button>}{reply.canEdit && canParticipate && <><button className="icon-button" title={tr("Editează răspunsul", "Edit reply")} aria-label={tr("Editează răspunsul", "Edit reply")} onClick={() => { setEditReply(reply); setReplyEditBody(reply.body); }}><Pencil size={15}/></button><button className="icon-button" title={tr("Șterge răspunsul", "Remove reply")} aria-label={tr("Șterge răspunsul", "Remove reply")} onClick={() => setRemove(reply)}><Trash2 size={15}/></button></>}{!reply.hidden && <ReportButton kind="reply" id={reply.id}/>}</div></div></article>)}</div>
    {canParticipate && <form className="community-reply-form" onSubmit={event => { event.preventDefault(); void action.run(async () => { await api(`community/topics/${id}/replies`, { method: "POST", body: { body: replyBody } }); setReplyBody(""); resource.reload(); }); }}><Field label={tr("Răspunsul tău", "Your reply")} required><textarea required minLength={2} maxLength={8000} rows={5} value={replyBody} onChange={event => setReplyBody(event.target.value)}/></Field><div className="row-actions end"><button className="button primary" disabled={action.busy || replyBody.trim().length < 2}>{action.busy ? <BusyIcon/> : <Send size={16}/>} {tr("Publică răspunsul", "Post reply")}</button></div></form>}
    </section><CommunityRules access={policy.data}/>
    {edit && <TopicComposer topic={topic} kind={topic.kind} close={() => setEdit(false)} saved={() => { setEdit(false); resource.reload(); }}/>} 
    {editReply && <Modal title={tr("Editează răspunsul", "Edit reply")} close={() => { if (!action.busy) setEditReply(null); }}><form onSubmit={event => { event.preventDefault(); void action.run(async () => { await api(`community/replies/${editReply.id}`, { method: "PATCH", body: { action: "edit", revision: editReply.revision, body: replyEditBody } }); setEditReply(null); resource.reload(); }); }}><Field label={tr("Răspuns", "Reply")}><textarea required minLength={2} maxLength={8000} rows={6} value={replyEditBody} onChange={event => setReplyEditBody(event.target.value)}/></Field>{Boolean(action.error) && <ErrorBox error={action.error}/>}<div className="row-actions end"><button className="button primary" disabled={action.busy}>{tr("Salvează", "Save")}</button></div></form></Modal>}
    {remove && <Modal title={tr("Șterge contribuția", "Remove contribution")} close={() => { if (!action.busy) setRemove(null); }}><p>{tr("Conținutul nu va mai fi vizibil comunității. Înregistrarea de audit este păstrată.", "This content will no longer be visible to the community. The audit record is retained.")}</p>{Boolean(action.error) && <ErrorBox error={action.error}/>}<div className="row-actions end"><button className="button" disabled={action.busy} onClick={() => setRemove(null)}>{tr("Renunță", "Cancel")}</button><button className="button danger" disabled={action.busy} onClick={() => void action.run(async () => { await api(remove === "topic" ? `community/topics/${id}` : `community/replies/${remove.id}`, { method: "PATCH", body: { action: "remove", revision: remove === "topic" ? topic.revision : remove.revision } }); if (remove === "topic") router.push("/community"); else { setRemove(null); resource.reload(); } })}><Trash2 size={16}/>{tr("Șterge", "Remove")}</button></div></Modal>}
  </div>;
}