"use client";

import { useState } from "react";
import { Check, Eye, EyeOff, Send, ShieldCheck, X } from "lucide-react";
import { api } from "@/lib/client";
import type { CommunityPolicy, CommunityReport } from "@/lib/community-contracts";
import { formatDate } from "@/lib/presentation";
import { useLanguage } from "../LanguageProvider";
import { useMarketplace, useResource } from "../MarketplaceProvider";
import { BusyIcon, EmptyState, ErrorBox, Field, Loading, Modal, Toggle, useText } from "../ui";
import { useCommunityAction, type CommunityAccess } from "./shared";

type ReportView = CommunityReport & { content: string; hidden: boolean; available: boolean };

function PolicyEditor({ access, saved }: { access: CommunityAccess; saved: () => void }) {
  const tr = useText(); const action = useCommunityAction(); const [policy, setPolicy] = useState<CommunityPolicy>(access.policy); const [success, setSuccess] = useState(false);
  return <section className="section-block"><h2>{tr("Politica comunității", "Community policy")}</h2><form className="form-stack community-form" onSubmit={event => { event.preventDefault(); void action.run(async () => { await api("community/policy", { method: "PUT", body: { policy, revision: access.revision } }); setSuccess(true); saved(); }); }}><fieldset className="editor-fields form-stack" disabled={action.busy}>
    {Boolean(action.error) && <ErrorBox error={action.error}/>} {success && <p className="success-notice" role="status">{tr("Politică salvată", "Policy saved")}</p>}
    <Toggle label={tr("Comunitate activă", "Community enabled")} checked={policy.enabled} onChange={enabled => setPolicy({ ...policy, enabled })}/><Toggle label={tr("Contribuții permise invitaților B2B", "Allow B2B guests to contribute")} checked={policy.allowGuestParticipation} onChange={allowGuestParticipation => setPolicy({ ...policy, allowGuestParticipation })}/>
    <Field label={tr("Reguli comunitare", "Community rules")} required><textarea required minLength={20} maxLength={8000} rows={6} value={policy.rules} onChange={event => setPolicy({ ...policy, rules: event.target.value })}/></Field><div className="row-actions end"><button className="button primary">{action.busy ? <BusyIcon/> : <Check size={16}/>} {tr("Salvează politica", "Save policy")}</button></div>
  </fieldset></form></section>;
}

export function CommunityModeration({ access, refreshPolicy }: { access: CommunityAccess; refreshPolicy: () => void }) {
  const tr = useText(); const { locale } = useLanguage(); const { data: bootstrap } = useMarketplace(); const resource = useResource<ReportView[]>("community/reports"); const action = useCommunityAction();
  const [status, setStatus] = useState("pending"); const [decision, setDecision] = useState<{ report: ReportView; action: "hide" | "restore" | "dismiss" } | null>(null); const [note, setNote] = useState(""); const [dispatch, setDispatch] = useState<{ processed: number; sent: number; failed: number } | null>(null);
  const reports = resource.data?.filter(report => !status || report.state === status) ?? [];
  return <><div className="section-heading"><h2><ShieldCheck size={21}/> {tr("Moderare", "Moderation")}</h2><select value={status} onChange={event => setStatus(event.target.value)} aria-label={tr("Stare rapoarte", "Report status")}><option value="pending">{tr("În așteptare", "Pending")}</option><option value="resolved">{tr("Rezolvate", "Resolved")}</option><option value="dismissed">{tr("Respinse", "Dismissed")}</option><option value="">{tr("Toate", "All")}</option></select></div>
    {Boolean(action.error) && !decision && <ErrorBox error={action.error}/>}
    {resource.loading ? <Loading/> : resource.error ? <ErrorBox error={resource.error} retry={resource.reload}/> : reports.length ? <div className="community-list">{reports.map(report => <article className="moderation-report" key={report.id}><div className="section-heading"><h3>{({ topic: tr("Discuție sau idee", "Discussion or idea"), reply: tr("Răspuns", "Reply"), profile: tr("Profil", "Profile"), team: tr("Echipă", "Team") })[report.targetKind]}</h3><span className="small-text muted">{report.hidden ? tr("Ascuns", "Hidden") : report.available ? tr("Vizibil", "Visible") : tr("Eliminat de autor", "Removed by author")}</span></div><p className="prose moderation-content">{report.content}</p><div className="community-meta"><span>{tr("Raportat de", "Reported by")} {report.reporterName}</span><time dateTime={report.createdAt}>{formatDate(report.createdAt, locale, true)}</time></div><p className="prose"><strong>{tr("Motiv", "Reason")}: </strong>{report.reason}</p>{report.resolution && <p className="prose"><strong>{report.resolvedBy}: </strong>{report.resolution}</p>}<div className="row-actions end">{report.available && <button className="button small" onClick={() => { setNote(""); setDecision({ report, action: report.hidden ? "restore" : "hide" }); }}>{report.hidden ? <Eye size={16}/> : <EyeOff size={16}/>} {report.hidden ? tr("Restaurează", "Restore") : tr("Ascunde", "Hide")}</button>}{report.state === "pending" && <button className="button small" onClick={() => { setNote(""); setDecision({ report, action: "dismiss" }); }}><X size={16}/>{tr("Respinge raportul", "Dismiss report")}</button>}</div></article>)}</div> : <EmptyState title={tr("Niciun raport în această stare", "No reports with this status")}/>}
    {bootstrap?.actor?.role === "admin" && <><PolicyEditor key={access.revision} access={access} saved={refreshPolicy}/><section className="section-block"><div className="section-heading"><h2>{tr("Livrare notificări", "Notification delivery")}</h2><button className="button" disabled={action.busy} onClick={() => void action.run(async () => { setDispatch(await api("community/delivery", { method: "POST", body: {} })); })}>{action.busy ? <BusyIcon/> : <Send size={16}/>} {tr("Procesează coada", "Process queue")}</button></div>{dispatch && <p role="status">{tr("Procesate", "Processed")}: {dispatch.processed} · {tr("Acceptate de furnizor", "Accepted by provider")}: {dispatch.sent} · {tr("Eșuate", "Failed")}: {dispatch.failed}</p>}</section></>}
    {decision && <Modal title={decision.action === "hide" ? tr("Ascunde conținutul", "Hide content") : decision.action === "restore" ? tr("Restaurează conținutul", "Restore content") : tr("Respinge raportul", "Dismiss report")} close={() => { if (!action.busy) setDecision(null); }}><form className="form-stack" onSubmit={event => { event.preventDefault(); void action.run(async () => { await api(`community/reports/${decision.report.id}`, { method: "PATCH", body: { action: decision.action, revision: decision.report.revision, note } }); setDecision(null); resource.reload(); }); }}>{Boolean(action.error) && <ErrorBox error={action.error}/>}<Field label={tr("Motivul deciziei", "Decision reason")} required><textarea required minLength={10} maxLength={2000} rows={5} value={note} onChange={event => setNote(event.target.value)}/></Field><div className="row-actions end"><button type="button" className="button" disabled={action.busy} onClick={() => setDecision(null)}>{tr("Renunță", "Cancel")}</button><button className="button primary" disabled={action.busy || note.trim().length < 10}>{action.busy ? <BusyIcon/> : <Check size={16}/>} {tr("Confirmă decizia", "Confirm decision")}</button></div></form></Modal>}
  </>;
}