"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Archive, ArrowRightLeft, Check, Pencil, Plus, Search, UserMinus, UserPlus, Users } from "lucide-react";
import { api } from "@/lib/client";
import type { AgentSummary } from "@/lib/contracts";
import type { Audience, CommunityProfile, CommunityTeam, ProfileInput } from "@/lib/community-contracts";
import { useMarketplace, useResource } from "../MarketplaceProvider";
import { AgentArtwork, BusyIcon, EmptyState, ErrorBox, Field, Loading, Modal, Toggle, useText } from "../ui";
import { AudienceField, Contributor, FollowButton, ReportButton, useCommunityAction, type CommunityAccess } from "./shared";

const skillsFrom = (value: string) => [...new Set(value.split(",").map(skill => skill.trim()).filter(Boolean))].slice(0, 12);
function Skills({ values }: { values: string[] }) { return <div className="tag-list">{values.map(value => <span key={value}>{value}</span>)}</div>; }

function ProfileEditor({ original, saved, close }: { original: CommunityProfile; saved: (profile: CommunityProfile) => void; close: () => void }) {
  const tr = useText(); const action = useCommunityAction(); const [values, setValues] = useState<ProfileInput>({ headline: original.headline, bio: original.bio, skills: original.skills, audience: original.audience, published: original.published }); const [skills, setSkills] = useState(original.skills.join(", "));
  return <form className="form-stack community-form" onSubmit={event => { event.preventDefault(); void action.run(async () => { saved(await api<CommunityProfile>("community/profiles/me", { method: "PUT", body: { profile: { ...values, skills: skillsFrom(skills) }, revision: original.revision } })); }); }}><fieldset className="editor-fields form-stack" disabled={action.busy}>
    {Boolean(action.error) && <ErrorBox error={action.error}/>}
    <Field label={tr("Rol profesional", "Professional headline")}><input maxLength={120} value={values.headline} onChange={event => setValues({ ...values, headline: event.target.value })}/></Field>
    <Field label={tr("Despre mine", "About me")}><textarea rows={6} maxLength={2000} value={values.bio} onChange={event => setValues({ ...values, bio: event.target.value })}/></Field>
    <Field label={tr("Competențe, separate prin virgulă", "Skills, comma separated")}><input maxLength={480} value={skills} onChange={event => setSkills(event.target.value)}/></Field>
    <AudienceField value={values.audience} onChange={audience => setValues({ ...values, audience })}/>
    <Toggle label={tr("Profil publicat în comunitate", "Profile published to the community")} checked={values.published} onChange={published => setValues({ ...values, published })}/>
    <div className="row-actions end"><button type="button" className="button" onClick={close}>{tr("Renunță", "Cancel")}</button><button className="button primary">{action.busy ? <BusyIcon/> : <Check size={16}/>} {tr("Salvează profilul", "Save profile")}</button></div>
  </fieldset></form>;
}

export function CommunityProfilePage({ id }: { id: string }) {
  const tr = useText(); const { data: bootstrap } = useMarketplace();
  const resource = useResource<CommunityProfile>(`community/profiles/${encodeURIComponent(id)}`); const policy = useResource<CommunityAccess>("community/policy");
  const agents = useResource<AgentSummary[]>(resource.data ? `community/profiles/${encodeURIComponent(id)}/agents` : null);
  const [editing, setEditing] = useState(false); const [saved, setSaved] = useState(false);
  if (resource.loading) return <div className="page-width page-content"><Loading/></div>;
  const profile = resource.data;
  if (resource.error || !profile) return <div className="page-width page-content"><Link href="/community?tab=people">{tr("Comunitate", "Community")}</Link><EmptyState title={tr("Profilul nu este publicat pentru audiența ta", "This profile is not published for your audience")}/></div>;
  const mine = bootstrap?.actor?.id === profile.id;
  return <div className="page-width page-content community-detail"><div className="breadcrumbs"><Link href="/community?tab=people">{tr("Creatori și membri", "Creators and members")}</Link><span>/</span><span>{profile.name}</span></div><div className="profile-heading"><span className="community-avatar large">{profile.name.split(" ").map(part => part[0]).slice(0, 2).join("")}</span><div><h1>{profile.name}</h1><p>{profile.headline}</p><span className="small-text muted">{profile.guest ? "B2B" : tr("Membru intern", "Internal member")}</span></div><div className="row-actions">{mine && policy.data?.canParticipate && <button className="button" onClick={() => setEditing(!editing)}><Pencil size={16}/>{tr("Editează profilul", "Edit profile")}</button>}{!mine && profile.published && !profile.hidden && <><FollowButton target={{ kind: "profile", id: profile.id }}/><ReportButton kind="profile" id={profile.id}/></>}</div></div>
    {saved && <div role="status" className="success-notice"><Check size={16}/>{tr("Profil salvat", "Profile saved")}</div>}
    {(!profile.published || profile.hidden) && <div className="info-notice">{profile.hidden ? tr("Profil ascuns de moderatori", "Profile hidden by moderators") : tr("Profil nepublicat", "Unpublished profile")}</div>}
    {editing ? <ProfileEditor original={profile} close={() => setEditing(false)} saved={updated => { resource.setData(updated); setEditing(false); setSaved(true); }}/> : <section className="section-block"><h2>{tr("Despre", "About")}</h2><p className="prose">{profile.bio || tr("Nicio prezentare adăugată", "No introduction added")}</p><Skills values={profile.skills}/></section>}
    <section className="section-block"><h2>{tr("Agenți publicați", "Published agents")}</h2>{agents.loading ? <Loading/> : agents.error ? <ErrorBox error={agents.error} retry={agents.reload}/> : agents.data?.length ? <div className="community-list">{agents.data.map(agent => <article className="community-row" key={agent.id}><AgentArtwork iconId={agent.iconId} platform={agent.platform}/><div><h3><Link href={`/agents/${agent.id}`}>{agent.name}</Link></h3><p className="muted">{agent.summary}</p></div></article>)}</div> : <p className="muted">{tr("Niciun agent publicat vizibil", "No visible published agents")}</p>}</section>
  </div>;
}

export function PeopleList() {
  const tr = useText(); const resource = useResource<CommunityProfile[]>("community/profiles"); const [query, setQuery] = useState("");
  const profiles = resource.data?.filter(profile => `${profile.name} ${profile.headline} ${profile.skills.join(" ")}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())) ?? [];
  return <><div className="section-heading"><h2>{tr("Creatori și membri", "Creators and members")}</h2><Link className="button small" href="/community/people/me"><Pencil size={15}/>{tr("Profilul meu", "My profile")}</Link></div><div className="catalog-search compact"><Search size={17}/><input aria-label={tr("Caută membri și competențe", "Search members and skills")} value={query} onChange={event => setQuery(event.target.value)}/></div>{resource.loading ? <Loading/> : resource.error ? <ErrorBox error={resource.error} retry={resource.reload}/> : profiles.length ? <div className="people-grid">{profiles.map(profile => <article className="person-entry" key={profile.id}><span className="community-avatar">{profile.name.split(" ").map(part => part[0]).slice(0, 2).join("")}</span><div><h3><Contributor id={profile.id} name={profile.name}/></h3><p>{profile.headline}</p><Skills values={profile.skills}/></div></article>)}</div> : <EmptyState title={tr("Niciun profil publicat găsit", "No published profiles found")}/>}</>;
}

function TeamEditor({ original, close, saved }: { original?: CommunityTeam; close: () => void; saved: (team: CommunityTeam) => void }) {
  const tr = useText(); const action = useCommunityAction(); const [name, setName] = useState(original?.name ?? ""); const [description, setDescription] = useState(original?.description ?? ""); const [audience, setAudience] = useState<Audience>(original?.audience ?? "members"); const [skills, setSkills] = useState(original?.skills.join(", ") ?? "");
  return <Modal title={original ? tr("Editează echipa", "Edit team") : tr("Creează o echipă", "Create team")} close={() => { if (!action.busy) close(); }}><form className="form-stack" onSubmit={event => { event.preventDefault(); void action.run(async () => { const team = { name, description, audience, skills: skillsFrom(skills) }; saved(await api<CommunityTeam>(original ? `community/teams/${original.id}` : "community/teams", { method: original ? "PATCH" : "POST", body: original ? { action: "edit", revision: original.revision, team } : team })); }); }}><fieldset className="editor-fields form-stack" disabled={action.busy}>
    {Boolean(action.error) && <ErrorBox error={action.error}/>}<Field label={tr("Numele echipei", "Team name")} required><input required minLength={2} maxLength={80} value={name} onChange={event => setName(event.target.value)}/></Field><Field label={tr("Despre echipă", "About the team")} required><textarea required minLength={10} maxLength={4000} rows={5} value={description} onChange={event => setDescription(event.target.value)}/></Field><Field label={tr("Competențe, separate prin virgulă", "Skills, comma separated")}><input maxLength={480} value={skills} onChange={event => setSkills(event.target.value)}/></Field><AudienceField value={audience} onChange={setAudience} disabled={Boolean(original)}/><div className="row-actions end"><button type="button" className="button" onClick={close}>{tr("Renunță", "Cancel")}</button><button className="button primary">{action.busy ? <BusyIcon/> : <Check size={16}/>} {tr("Salvează echipa", "Save team")}</button></div>
  </fieldset></form></Modal>;
}

export function TeamsList() {
  const tr = useText(); const router = useRouter(); const { data: bootstrap } = useMarketplace(); const policy = useResource<CommunityAccess>("community/policy"); const resource = useResource<CommunityTeam[]>("community/teams"); const [query, setQuery] = useState(""); const [create, setCreate] = useState(false);
  const teams = resource.data?.filter(team => `${team.name} ${team.description} ${team.skills.join(" ")}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())) ?? [];
  return <><div className="section-heading"><h2>{tr("Echipe comunitare", "Community teams")}</h2>{policy.data?.canParticipate && bootstrap?.actor && !bootstrap.actor.guest && bootstrap.actor.role !== "reader" && <button className="button primary small" onClick={() => setCreate(true)}><Plus size={16}/>{tr("Creează o echipă", "Create team")}</button>}</div><div className="catalog-search compact"><Search size={17}/><input aria-label={tr("Caută echipe", "Search teams")} value={query} onChange={event => setQuery(event.target.value)}/></div>{resource.loading ? <Loading/> : resource.error ? <ErrorBox error={resource.error} retry={resource.reload}/> : teams.length ? <div className="community-list">{teams.map(team => <article className="community-row" key={team.id}><span className="community-row-icon"><Users size={24}/></span><div className="community-row-body"><h2><Link href={`/community/teams/${team.id}`}>{team.name}</Link></h2><p className="community-excerpt">{team.description}</p><Skills values={team.skills}/><small className="muted">{team.members.length} {tr("membri", "members")}</small></div></article>)}</div> : <EmptyState title={tr("Nicio echipă găsită", "No teams found")}/>} {create && <TeamEditor close={() => setCreate(false)} saved={team => { setCreate(false); resource.reload(); router.push(`/community/teams/${team.id}`); }}/>}</>;
}

export function CommunityTeamPage({ id }: { id: string }) {
  const tr = useText(); const router = useRouter(); const { data: bootstrap } = useMarketplace(); const resource = useResource<CommunityTeam>(`community/teams/${id}`); const policy = useResource<CommunityAccess>("community/policy"); const action = useCommunityAction();
  const [editing, setEditing] = useState(false); const [manage, setManage] = useState<"transfer" | "archive" | null>(null); const [ownerId, setOwnerId] = useState("");
  if (resource.loading) return <div className="page-width page-content"><Loading/></div>;
  if (resource.error || !resource.data) return <div className="page-width page-content"><ErrorBox error={resource.error ?? "Team unavailable"} retry={resource.reload}/><Link href="/community?tab=teams">{tr("Înapoi la echipe", "Back to teams")}</Link></div>;
  const team = resource.data; const actor = bootstrap?.actor; const owner = actor && !actor.guest && (team.ownerId === actor.id || actor.role === "admin"); const joined = team.members.some(member => member.id === actor?.id);
  return <div className="page-width page-content community-detail"><div className="breadcrumbs"><Link href="/community?tab=teams">{tr("Echipe", "Teams")}</Link><span>/</span><span>{team.name}</span></div><div className="profile-heading"><span className="community-avatar large"><Users size={34}/></span><div><h1>{team.name}</h1><p>{tr("Responsabil", "Owner")}: <Contributor id={team.ownerId} name={team.ownerName}/></p></div><div className="row-actions">{owner && policy.data?.canParticipate && <button className="button" onClick={() => setEditing(true)}><Pencil size={16}/>{tr("Editează echipa", "Edit team")}</button>}</div></div>
    {team.hidden && <div className="info-notice">{tr("Echipă ascunsă de moderatori", "Team hidden by moderators")}</div>}{Boolean(action.error) && <ErrorBox error={action.error}/>}
    <div className="community-detail-tools">{!team.hidden && <FollowButton target={{ kind: "team", id }}/>} {policy.data?.canParticipate && !team.hidden && team.ownerId !== actor?.id && <button className="button primary" disabled={action.busy} onClick={() => void action.run(async () => { await api(`community/teams/${id}/membership`, { method: "PUT", body: { joined: !joined } }); resource.reload(); })}>{joined ? <UserMinus size={16}/> : <UserPlus size={16}/>} {joined ? tr("Părăsește echipa", "Leave team") : tr("Alătură-te echipei", "Join team")}</button>}{!team.hidden && <ReportButton kind="team" id={id}/>}</div>
    <section className="section-block"><p className="prose">{team.description}</p><Skills values={team.skills}/><p className="small-text muted">{team.audience === "all" ? tr("Echipă deschisă membrilor și invitaților B2B autorizați", "Team open to members and authorized B2B guests") : tr("Echipă pentru membri interni", "Internal member team")}</p></section>
    <section className="section-block"><h2>{tr("Membri", "Members")} <span className="muted">{team.members.length}</span></h2><div className="people-grid">{team.members.map(member => <div className="person-entry" key={member.id}><span className="community-avatar">{member.name.split(" ").map(part => part[0]).slice(0, 2).join("")}</span><Contributor id={member.id} name={member.name}/></div>)}</div></section>
    {owner && <div className="row-actions"><button className="button" onClick={() => setManage("transfer")}><ArrowRightLeft size={16}/>{tr("Transferă responsabilitatea", "Transfer ownership")}</button><button className="button danger" onClick={() => setManage("archive")}><Archive size={16}/>{tr("Arhivează echipa", "Archive team")}</button></div>}
    {editing && <TeamEditor original={team} close={() => setEditing(false)} saved={updated => { resource.setData(updated); setEditing(false); }}/>} {manage && <Modal title={manage === "transfer" ? tr("Transferă responsabilitatea", "Transfer ownership") : tr("Arhivează echipa", "Archive team")} close={() => { if (!action.busy) setManage(null); }}><form onSubmit={event => { event.preventDefault(); void action.run(async () => { await api(`community/teams/${id}`, { method: "PATCH", body: { action: manage, revision: team.revision, ...(manage === "transfer" ? { ownerId } : {}) } }); if (manage === "archive") router.push("/community?tab=teams"); else { setManage(null); resource.reload(); } }); }}>{manage === "transfer" ? <Field label={tr("Noul responsabil", "New owner")} required><select required value={ownerId} onChange={event => setOwnerId(event.target.value)}><option value="">{tr("Selectează un membru intern", "Select an internal member")}</option>{team.members.filter(member => member.id !== team.ownerId).map(member => <option value={member.id} key={member.id}>{member.name}</option>)}</select></Field> : <p>{tr("Echipa nu va mai fi afișată în comunitate. Agenții publicați nu sunt modificați.", "The team will no longer appear in the community. Published agents are not changed.")}</p>}{Boolean(action.error) && <ErrorBox error={action.error}/>}<div className="row-actions end"><button type="button" className="button" onClick={() => setManage(null)}>{tr("Renunță", "Cancel")}</button><button className="button primary" disabled={action.busy}><Check size={16}/>{tr("Confirmă", "Confirm")}</button></div></form></Modal>}
  </div>;
}