"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronRight, FileCheck2, Plus, Save, Send, Trash2, Undo2, X } from "lucide-react";
import { api } from "@/lib/client";
import { categoryIds, draftSchema, newDraft, submissionIssues, type AgentDetail, type AgentDraft, type AgentRecord, type ComponentDefinition, type KnowledgeSource, type StoredFile } from "@/lib/contracts";
import { categoryName, errorText, formatDate } from "@/lib/presentation";
import { useLanguage } from "./LanguageProvider";
import { useMarketplace } from "./MarketplaceProvider";
import { AgentArtwork, Badge, BusyIcon, ErrorBox, Field, Loading, Toggle, useText } from "./ui";
import { ConfigurationView } from "./ConfigurationView";
import { UploadControl } from "./UploadControl";

type Issue = { field: string; message: string };
const stepFields = [["platform", "name", "summary", "description", "overview", "category", "tags", "iconId"], ["instructions", "builder", "studio", "environment", "authentication", "topics", "tools", "connectionReferences", "environmentVariables"], ["knowledge", "prompts"], ["distribution", "package", "solution", "license", "limitations", "language", "releaseNotes"]];
export function editorIssues(draft: AgentDraft): Issue[] {
  const parsed = draftSchema.safeParse(draft);
  return [...(parsed.success ? [] : parsed.error.issues.map((issue) => ({ field: issue.path.join("."), message: issue.message }))), ...submissionIssues(draft)];
}

function ListEditor({ label, value, onChange, maximum = 30 }: { label: string; value: string[]; onChange: (value: string[]) => void; maximum?: number }) {
  const [input, setInput] = useState(""); const tr = useText();
  const add = () => { const item = input.trim(); if (item && !value.includes(item) && value.length < maximum) { onChange([...value, item]); setInput(""); } };
  return <div className="field"><span className="field-label">{label}</span><div className="inline-input"><input aria-label={label} value={input} maxLength={label === "Tags" ? 60 : 500} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); add(); } }}/><button type="button" className="icon-button" aria-label={`${tr("Adaugă", "Add")} ${label}`} title={`${tr("Adaugă", "Add")} ${label}`} disabled={!input.trim() || value.length >= maximum} onClick={add}><Plus size={18}/></button></div><div className="tag-list">{value.map((item, index) => <span key={index}>{item}<button type="button" title={`${tr("Elimină", "Remove")} ${item}`} aria-label={`${tr("Elimină", "Remove")} ${item}`} onClick={() => onChange(value.filter((_, position) => position !== index))}><X size={12}/></button></span>)}</div></div>;
}

function ComponentEditor({ label, entries, onChange }: { label: string; entries: ComponentDefinition[]; onChange: (value: ComponentDefinition[]) => void }) {
  const tr = useText();
  return <section className="section-block"><div className="section-heading"><h3>{label} <span className="muted">({entries.length})</span></h3><button type="button" className="button quiet small" disabled={entries.length >= 100} onClick={() => onChange([...entries, { name: "", configuration: "" }])}><Plus size={15}/>{tr("Adaugă", "Add")}</button></div>{entries.map((entry, index) => <div className="repeatable-entry" key={index}><div className="entry-heading"><strong>{label} {index + 1}</strong><button type="button" className="icon-button" title={tr("Elimină componenta", "Remove component")} aria-label={`${tr("Elimină", "Remove")} ${label} ${index + 1}`} onClick={() => onChange(entries.filter((_, position) => position !== index))}><Trash2 size={16}/></button></div><div className="form-stack"><Field label="Name" required><input maxLength={200} value={entry.name} onChange={(event) => onChange(entries.map((item, position) => position === index ? { ...item, name: event.target.value } : item))}/></Field><Field label={tr("Configurație exactă / asociere necesară", "Exact configuration / required binding")} required><textarea rows={5} maxLength={32000} spellCheck={false} value={entry.configuration} onChange={(event) => onChange(entries.map((item, position) => position === index ? { ...item, configuration: event.target.value } : item))}/></Field></div></div>)}</section>;
}

function KnowledgeEditor({ entries, onChange, maximum }: { entries: KnowledgeSource[]; onChange: (value: KnowledgeSource[]) => void; maximum: number }) {
  const tr = useText();
  const update = (index: number, key: keyof KnowledgeSource, value: string) => onChange(entries.map((entry, position) => position === index ? { ...entry, [key]: value } : entry));
  return <section className="section-block"><div className="section-heading"><h3>Knowledge <span className="muted">({entries.length}/{maximum})</span></h3><button className="button quiet small" type="button" disabled={entries.length >= maximum} onClick={() => onChange([...entries, { type: "", name: "", location: "", settings: "" }])}><Plus size={15}/>{tr("Adaugă sursă", "Add source")}</button></div><datalist id="knowledge-types">{["SharePoint", "Work content · Outlook", "Work content · Teams", "Public website", "Microsoft 365 Copilot connector", "Dataverse", "File"].map((type) => <option key={type} value={type}/>)}</datalist>{entries.map((entry, index) => <div className="repeatable-entry" key={index}><div className="entry-heading"><strong>{tr("Sursă", "Source")} {index + 1}</strong><button className="icon-button" type="button" title={tr("Elimină sursa", "Remove source")} aria-label={`${tr("Elimină sursa", "Remove source")} ${index + 1}`} onClick={() => onChange(entries.filter((_, position) => position !== index))}><Trash2 size={16}/></button></div><div className="form-grid"><Field label={tr("Tip", "Type")} required><input list="knowledge-types" maxLength={100} value={entry.type} onChange={(event) => update(index, "type", event.target.value)}/></Field><Field label="Name" required><input maxLength={200} value={entry.name} onChange={(event) => update(index, "name", event.target.value)}/></Field><div className="span-all"><Field label={tr("Locație / domeniu exact", "Exact location / scope")} required><input maxLength={2000} value={entry.location} onChange={(event) => update(index, "location", event.target.value)} spellCheck={false}/></Field></div><div className="span-all"><Field label={tr("Setări și permisiuni necesare", "Settings and required permissions")}><textarea rows={3} maxLength={8000} value={entry.settings} onChange={(event) => update(index, "settings", event.target.value)}/></Field></div></div></div>)}</section>;
}

export function AgentEditor() {
  const params = useSearchParams(); const requestedId = params.get("id");
  const { locale } = useLanguage(); const tr = useText(); const { data: bootstrap, reload: reloadBootstrap } = useMarketplace();
  const [draft, setDraft] = useState<AgentDraft>(() => newDraft()); const [record, setRecord] = useState<AgentRecord | null>(null);
  const [snapshot, setSnapshot] = useState(() => JSON.stringify(newDraft())); const [step, setStep] = useState(0); const [visited, setVisited] = useState(0);
  const [loading, setLoading] = useState(Boolean(requestedId)); const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState(false);
  const [error, setError] = useState<unknown>(null); const [issues, setIssues] = useState<Issue[]>([]); const [message, setMessage] = useState("");
  const [iconFile, setIconFile] = useState<StoredFile | null>(null); const [packageFile, setPackageFile] = useState<StoredFile | null>(null);
  const [confirmed, setConfirmed] = useState(false); const loadedId = useRef<string | null | undefined>(undefined);
  const formTop = useRef<HTMLDivElement>(null);
  const dirty = snapshot !== JSON.stringify(draft);
  const locked = record?.state === "in-review" || record?.state === "archived";
  const steps = [tr("Identificare", "Identity"), tr("Configurare", "Configuration"), "Knowledge & prompts", tr("Distribuire", "Distribution"), tr("Verificare", "Review")];
  useEffect(() => {
    if (requestedId === loadedId.current) return;
    const controller = new AbortController(); setError(null); setMessage(""); setStep(0); setVisited(0); setConfirmed(false);
    if (!requestedId) { const empty = newDraft(); loadedId.current = null; setDraft(empty); setSnapshot(JSON.stringify(empty)); setRecord(null); setLoading(false); return; }
    setLoading(true);
    api<AgentDetail>(`agents/${encodeURIComponent(requestedId)}?draft=true`, { signal: controller.signal }).then((detail) => {
      if (!detail.canEdit || !detail.record) throw new Error(tr("Doar creatorul poate edita acest agent.", "Only the publisher can edit this agent."));
      loadedId.current = requestedId; setRecord(detail.record); setDraft(detail.record.draft); setSnapshot(JSON.stringify(detail.record.draft)); setPackageFile(detail.file); setLoading(false);
    }).catch((failure) => { if (!controller.signal.aborted) { setError(failure); setLoading(false); } });
    return () => controller.abort();
  }, [requestedId, tr]);
  useEffect(() => {
    if (!dirty) return;
    const beforeUnload = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ""; };
    const navigate = (event: MouseEvent) => {
      const link = (event.target as HTMLElement).closest?.("a[href]") as HTMLAnchorElement | null;
      if (!link || link.target === "_blank" || link.hasAttribute("download") || event.ctrlKey || event.metaKey || event.shiftKey || link.href === window.location.href || link.hash && link.pathname === window.location.pathname) return;
      if (!window.confirm(tr("Există modificări nesalvate. Părăsești pagina?", "You have unsaved changes. Leave this page?"))) { event.preventDefault(); event.stopPropagation(); }
    };
    window.addEventListener("beforeunload", beforeUnload); document.addEventListener("click", navigate, true);
    return () => { window.removeEventListener("beforeunload", beforeUnload); document.removeEventListener("click", navigate, true); };
  }, [dirty, tr]);
  const update = <Key extends keyof AgentDraft>(key: Key, value: AgentDraft[Key]) => { setDraft((current) => ({ ...current, [key]: value })); setMessage(""); setConfirmed(false); };
  const studio = (key: keyof Extract<AgentDraft, { platform: "copilot-studio" }>["studio"], value: unknown) => setDraft((current) => current.platform === "copilot-studio" ? { ...current, studio: { ...current.studio, [key]: value } } : current);
  const distribution = <Key extends keyof AgentDraft["distribution"]>(key: Key, value: AgentDraft["distribution"][Key]) => update("distribution", { ...draft.distribution, [key]: value });
  const changeStep = (next: number) => { setStep(next); setIssues([]); formTop.current?.scrollIntoView({ block: "start" }); };
  const fieldError = (field: string) => issues.find((issue) => issue.field === field)?.message;
  const nextStep = () => {
    const found = editorIssues(draft).filter((issue) => stepFields[step]?.some((field) => issue.field === field || issue.field.startsWith(`${field}.`)));
    if (found.length) { setIssues(found); formTop.current?.scrollIntoView({ block: "start" }); return; }
    setVisited(Math.max(visited, step + 1)); changeStep(step + 1);
  };
  const persist = async () => {
    const parsed = draftSchema.safeParse(draft);
    if (!parsed.success) { setIssues(parsed.error.issues.map((issue) => ({ field: issue.path.join("."), message: issue.message }))); throw new Error("Check the required fields."); }
    const saved = await api<AgentRecord>(record ? `agents/${record.id}` : "agents", { method: record ? "PATCH" : "POST", body: record ? { action: "save", revision: record.revision, draft } : { draft } });
    setRecord(saved); setSnapshot(JSON.stringify(saved.draft)); loadedId.current = saved.id;
    window.history.replaceState(null, "", `/submit?id=${saved.id}`); return saved;
  };
  const save = async () => { setBusy(true); setError(null); setIssues([]); setMessage(""); try { await persist(); setMessage(tr("Ciornă salvată", "Draft saved")); } catch (failure) { setError(failure); } finally { setBusy(false); } };
  const submit = async () => {
    const found = editorIssues(draft); if (found.length) { setIssues(found); formTop.current?.scrollIntoView({ block: "start" }); return; }
    if (!confirmed) return;
    setBusy(true); setError(null); setMessage("");
    try { const saved = dirty || !record ? await persist() : record; const submitted = await api<AgentRecord>(`agents/${saved.id}`, { method: "PATCH", body: { action: "submit", revision: saved.revision } }); setRecord(submitted); setMessage(submitted.state === "published" ? tr("Versiune publicată", "Version published") : tr("Trimis spre revizuire", "Submitted for review")); await reloadBootstrap(); } catch (failure) { setError(failure); } finally { setBusy(false); }
  };
  const unlock = async () => { if (!record) return; setBusy(true); setError(null); try { setRecord(await api<AgentRecord>(`agents/${record.id}`, { method: "PATCH", body: { action: record.state === "archived" ? "restore" : "withdraw", revision: record.revision } })); await reloadBootstrap(); } catch (failure) { setError(failure); } finally { setBusy(false); } };
  if (loading) return <div className="page-width page-content"><Loading rows={5}/></div>;
  if (requestedId && !record && error) return <div className="page-width page-content"><ErrorBox error={error}/><Link href="/dashboard">{tr("Înapoi la spațiul meu", "Back to my workspace")}</Link></div>;
  const knowledge = draft.platform === "agent-builder" ? draft.builder.knowledge : draft.studio.knowledge;
  return <div className="page-width page-content editor-page">
    <div className="breadcrumbs"><Link href="/dashboard">{tr("Spațiul meu", "My workspace")}</Link><ChevronRight size={13}/><span>{record ? draft.name || tr("Ciornă", "Draft") : tr("Agent nou", "New agent")}</span></div>
    <div className="page-heading"><div><span className="eyebrow">{record ? `${tr("Revizie", "Revision")} ${record.revision}` : tr("Agent nou", "New agent")}</span><h1>{record ? tr("Editează agentul", "Edit agent") : tr("Publică un agent", "Publish an agent")}</h1></div><div className="row-actions">{record && <Badge value={record.state}/>}<button className="button" disabled={busy || uploading || locked} onClick={() => void save()}>{busy ? <BusyIcon/> : <Save size={16}/>} {tr("Salvează ciorna", "Save draft")}</button></div></div>
    <div className="editor-layout"><nav className="editor-steps" aria-label={tr("Pașii publicării", "Publication steps")}>{steps.map((label, index) => <button key={label} type="button" aria-current={step === index ? "step" : undefined} disabled={index > visited || busy || uploading} onClick={() => index <= visited && changeStep(index)}><span>{index < step ? <Check size={15}/> : index + 1}</span>{label}</button>)}<div className="editor-save-state" role="status">{dirty ? tr("Modificări nesalvate", "Unsaved changes") : record ? `${tr("Salvat", "Saved")} · ${formatDate(record.updatedAt, locale, true)}` : tr("Ciornă nouă", "New draft")}</div></nav>
    <div className="editor-main" ref={formTop}>
      {Boolean(error) && <ErrorBox error={error}/>} {message && <div className="success-notice" role="status"><Check size={17}/>{message}{record && <Link href={`/agents/${record.id}?draft=true`}>{tr("Deschide fișa", "Open details")}</Link>}</div>}
      {record?.reviewNote && <div className="info-notice"><FileCheck2 size={18}/><div><strong>{tr("Observații de revizuire", "Review notes")}</strong><p className="prose">{record.reviewNote}</p></div></div>}
      {locked && <div className="info-notice"><div><strong>{record?.state === "in-review" ? tr("Ciornă blocată pe durata revizuirii", "Draft locked during review") : tr("Agent arhivat", "Archived agent")}</strong><div className="row-actions"><button type="button" className="button small" disabled={busy} onClick={() => void unlock()}><Undo2 size={15}/>{record?.state === "in-review" ? tr("Retrage pentru editare", "Withdraw to edit") : tr("Restaurează", "Restore")}</button></div></div></div>}
      {issues.length > 0 && <div className="validation-summary" role="alert"><strong>{tr("Completează câmpurile necesare", "Complete the required fields")}</strong><ul className="field-error-list">{issues.map((issue, index) => <li key={index}><button type="button" onClick={() => { const target = stepFields.findIndex((fields) => fields.some((field) => issue.field === field || issue.field.startsWith(`${field}.`))); if (target >= 0) { setStep(target); setVisited(Math.max(visited, target)); } }}>{issue.field}: {errorText(issue.message, locale)}</button></li>)}</ul></div>}
      <fieldset className="editor-fields" disabled={busy || uploading || locked}><legend className="sr-only">{steps[step]}</legend>
      {step === 0 && <div className="form-stack"><h2>{steps[0]}</h2><fieldset className="platform-picker"><legend>{tr("Platformă", "Platform")}</legend>{["agent-builder", "copilot-studio"].map((platform) => <label key={platform} data-selected={draft.platform === platform}><input type="radio" name="platform" value={platform} checked={draft.platform === platform} disabled={Boolean(record)} onChange={() => { if (draft.platform === platform) return; if (dirty && !window.confirm(tr("Schimbarea platformei elimină configurația specifică. Continui?", "Switching platforms removes platform-specific configuration. Continue?"))) return; const blank = newDraft(platform as AgentDraft["platform"]); const { platform: previousPlatform, ...common } = draft; void previousPlatform; const clean = Object.fromEntries(Object.entries(common).filter(([key]) => key !== "builder" && key !== "studio")); setDraft({ ...blank, ...clean, distribution: { ...draft.distribution, downloadEnabled: false, packageId: "" } } as AgentDraft); }}/><AgentArtwork platform={platform}/><strong>{platform === "agent-builder" ? "M365 Copilot · Agent Builder" : "Copilot Studio"}</strong></label>)}</fieldset>
        <Field label="Name" required error={fieldError("name")} hint={`${draft.name.length}/${draft.platform === "agent-builder" ? 30 : 100}`}><input autoComplete="off" maxLength={draft.platform === "agent-builder" ? 30 : 100} value={draft.name} onChange={(event) => update("name", event.target.value)}/></Field>
        <Field label={tr("Rezumat marketplace", "Marketplace summary")} required error={fieldError("summary")} hint={`${draft.summary.length}/240`}><textarea rows={2} maxLength={240} value={draft.summary} onChange={(event) => update("summary", event.target.value)}/></Field>
        <Field label="Description" required error={fieldError("description")} hint={`${draft.description.length}/${draft.platform === "agent-builder" ? 1000 : 4000}`}><textarea rows={4} maxLength={draft.platform === "agent-builder" ? 1000 : 4000} value={draft.description} onChange={(event) => update("description", event.target.value)} spellCheck={false}/></Field>
        <Field label={tr("Prezentare și cazuri de utilizare", "Overview and use cases")}><textarea rows={5} maxLength={8000} value={draft.overview} onChange={(event) => update("overview", event.target.value)}/></Field>
        <div className="form-grid"><Field label={tr("Categorie", "Category")}><select value={draft.category} onChange={(event) => update("category", event.target.value as AgentDraft["category"])}>{categoryIds.map((category) => <option key={category} value={category}>{categoryName(category, locale)}</option>)}</select></Field><ListEditor label="Tags" value={draft.tags} maximum={20} onChange={(value) => update("tags", value)}/></div>
        <UploadControl kind="icon" file={iconFile} onBusy={setUploading} onUploaded={(file) => { setIconFile(file); update("iconId", file.id); }}/>{draft.platform === "agent-builder" && <small className="muted">PNG · 192 × 192 px</small>}{draft.iconId && <div className="row-actions"><AgentArtwork iconId={draft.iconId} platform={draft.platform}/><button className="button quiet small" type="button" onClick={() => { update("iconId", ""); setIconFile(null); }}><Trash2 size={14}/>{tr("Elimină iconul", "Remove icon")}</button></div>}
      </div>}
      {step === 1 && <><h2>{steps[1]}</h2><section className="section-block"><Field label="Instructions" required error={fieldError("instructions")} hint={`${draft.instructions.length}/${draft.platform === "agent-builder" ? 8000 : 32000}`}><textarea className="code-input" rows={12} maxLength={draft.platform === "agent-builder" ? 8000 : 32000} value={draft.instructions} onChange={(event) => update("instructions", event.target.value)} spellCheck={false}/></Field></section>
      {draft.platform === "agent-builder" ? <div className="form-stack"><Field label="Model"><select value={draft.builder.model} onChange={(event) => setDraft({ ...draft, builder: { ...draft.builder, model: event.target.value as typeof draft.builder.model } })}><option>Auto</option><option>Quick response</option><option>Think deeper</option></select></Field><Toggle label="Only use specified knowledge" checked={draft.builder.onlyUseKnowledge} onChange={(value) => setDraft({ ...draft, builder: { ...draft.builder, onlyUseKnowledge: value } })}/><Toggle label="Create documents, charts, and code" checked={draft.builder.codeInterpreter} onChange={(value) => setDraft({ ...draft, builder: { ...draft.builder, codeInterpreter: value } })}/><Toggle label="Create images" checked={draft.builder.imageGenerator} onChange={(value) => setDraft({ ...draft, builder: { ...draft.builder, imageGenerator: value } })}/></div> : <>
      <section className="section-block"><div className="form-grid"><Field label="Source environment" required><input maxLength={200} value={draft.studio.environment} onChange={(event) => studio("environment", event.target.value)}/></Field><Field label="Environment ID" required><input maxLength={200} value={draft.studio.environmentId} onChange={(event) => studio("environmentId", event.target.value)}/></Field><Field label="Harness"><input maxLength={100} value={draft.studio.harness} onChange={(event) => studio("harness", event.target.value)}/></Field><Field label="Orchestration"><select value={draft.studio.orchestration} onChange={(event) => studio("orchestration", event.target.value)}><option>Generative</option><option>Classic</option></select></Field><div className="span-all"><Field label="Authentication" required><textarea rows={3} maxLength={2000} value={draft.studio.authentication} onChange={(event) => studio("authentication", event.target.value)}/></Field></div><div className="span-all"><ListEditor label="Channels" value={draft.studio.channels} onChange={(value) => studio("channels", value)}/></div></div></section>
      <ComponentEditor label="Topics" entries={draft.studio.topics} onChange={(value) => studio("topics", value)}/><ComponentEditor label="Tools / actions / flows" entries={draft.studio.tools} onChange={(value) => studio("tools", value)}/><ComponentEditor label="Connection references" entries={draft.studio.connectionReferences} onChange={(value) => studio("connectionReferences", value)}/><ComponentEditor label="Environment variables" entries={draft.studio.environmentVariables} onChange={(value) => studio("environmentVariables", value)}/><section className="section-block"><ListEditor label={tr("Dependențe", "Dependencies")} value={draft.studio.dependencies} maximum={100} onChange={(value) => studio("dependencies", value)}/></section></>}
      </>}
      {step === 2 && <><h2>Knowledge & prompts</h2><KnowledgeEditor entries={knowledge} maximum={draft.platform === "agent-builder" ? 20 : 100} onChange={(value) => setDraft(draft.platform === "agent-builder" ? { ...draft, builder: { ...draft.builder, knowledge: value } } : { ...draft, studio: { ...draft.studio, knowledge: value } })}/><section className="section-block"><div className="section-heading"><h3>Starter prompts ({draft.prompts.length}/12)</h3><button className="button quiet small" type="button" disabled={draft.prompts.length >= 12} onClick={() => update("prompts", [...draft.prompts, { title: "", message: "" }])}><Plus size={15}/>{tr("Adaugă prompt", "Add prompt")}</button></div>{draft.prompts.map((prompt, index) => <div className="repeatable-entry" key={index}><div className="entry-heading"><strong>Prompt {index + 1}</strong><button type="button" className="icon-button" title={tr("Elimină promptul", "Remove prompt")} aria-label={`${tr("Elimină promptul", "Remove prompt")} ${index + 1}`} onClick={() => update("prompts", draft.prompts.filter((_, position) => position !== index))}><Trash2 size={16}/></button></div><div className="form-stack"><Field label="Title" required><input maxLength={100} value={prompt.title} onChange={(event) => update("prompts", draft.prompts.map((item, position) => position === index ? { ...item, title: event.target.value } : item))}/></Field><Field label="Message" required><textarea rows={3} maxLength={2000} spellCheck={false} value={prompt.message} onChange={(event) => update("prompts", draft.prompts.map((item, position) => position === index ? { ...item, message: event.target.value } : item))}/></Field></div></div>)}</section></>}
      {step === 3 && <div className="form-stack"><h2>{steps[3]}</h2><Field label={tr("Linkul real al agentului (HTTPS)", "Actual agent launch URL (HTTPS)")}><input type="url" value={draft.distribution.launchUrl} maxLength={2000} onChange={(event) => distribution("launchUrl", event.target.value)} placeholder="https://"/></Field><Toggle label={tr("Acces la instanță prin cerere și confirmarea partajării", "Instance access requires a request and sharing confirmation")} checked={draft.distribution.requestAccess} onChange={(value) => distribution("requestAccess", value)}/><div className="form-grid"><Field label="Source agent ID"><input value={draft.distribution.sourceAgentId} maxLength={200} onChange={(event) => distribution("sourceAgentId", event.target.value)}/></Field><Field label="Microsoft catalog package ID"><input value={draft.distribution.registryPackageId} maxLength={200} onChange={(event) => distribution("registryPackageId", event.target.value)}/></Field></div>
        {draft.platform === "copilot-studio" && <section className="section-block"><Toggle label={tr("Soluție ZIP disponibilă pentru import", "Solution ZIP available for import")} checked={draft.distribution.downloadEnabled} disabled={bootstrap?.settings.downloadsEnabled === false} onChange={(value) => distribution("downloadEnabled", value)}/>{bootstrap?.settings.downloadsEnabled === false && <div className="info-notice">{tr("Descărcările sunt dezactivate de administrator.", "Downloads are disabled by the administrator.")}</div>}{draft.distribution.downloadEnabled && <div className="form-stack"><UploadControl kind="solution" file={packageFile} onBusy={setUploading} onUploaded={(file) => { setPackageFile(file); setDraft({ ...draft, distribution: { ...draft.distribution, packageId: file.id }, studio: { ...draft.studio, solutionName: file.solution!.uniqueName, solutionVersion: file.solution!.version, solutionType: file.solution!.managed ? "Managed" : "Unmanaged" } }); }}/><div className="form-grid"><Field label="Solution unique name" required><input readOnly value={draft.studio.solutionName}/></Field><Field label="Solution version" required><input readOnly value={draft.studio.solutionVersion}/></Field><Field label="Solution type"><input readOnly value={draft.studio.solutionType}/></Field></div>{packageFile && <p className="file-info">SHA-256: <code>{packageFile.sha256}</code></p>}</div>}</section>}
        <div className="form-grid"><Field label={tr("Licențe și condiții de utilizare", "Licensing and usage requirements")} required error={fieldError("license")}><textarea rows={3} maxLength={1000} value={draft.license} onChange={(event) => update("license", event.target.value)}/></Field><Field label={tr("Limba agentului", "Agent language")}><input maxLength={40} value={draft.language} onChange={(event) => update("language", event.target.value)}/></Field><div className="span-all"><Field label={tr("Limitări și riscuri cunoscute", "Known limitations and risks")}><textarea rows={4} maxLength={4000} value={draft.limitations} onChange={(event) => update("limitations", event.target.value)}/></Field></div></div>
        <Toggle label={tr("Vizibil invitaților B2B autorizați", "Visible to authorized B2B guests")} checked={draft.distribution.guestVisible} onChange={(value) => distribution("guestVisible", value)}/><Field label={tr("Acces la configurație și soluție", "Configuration and solution audience")}><select value={draft.distribution.configurationAudience} onChange={(event) => distribution("configurationAudience", event.target.value as "members" | "all")}><option value="members">{tr("Doar membri interni", "Internal members only")}</option><option value="all">{tr("Membri și invitați autorizați", "Members and authorized guests")}</option></select></Field><Field label={tr("Notele versiunii", "Release notes")}><textarea rows={4} maxLength={4000} value={draft.releaseNotes} onChange={(event) => update("releaseNotes", event.target.value)}/></Field>
      </div>}
      {step === 4 && <div className="form-stack"><h2>{steps[4]}</h2><dl className="definition-list"><dt>{tr("Creator", "Publisher")}</dt><dd>{bootstrap?.actor?.name}</dd><dt>{tr("Categorie", "Category")}</dt><dd>{categoryName(draft.category, locale)}</dd><dt>{tr("Licențe", "Licensing")}</dt><dd className="prose">{draft.license}</dd><dt>{tr("Acces", "Access")}</dt><dd>{draft.distribution.requestAccess ? tr("Cerere de acces", "Access request") : tr("Link direct", "Direct link")}</dd><dt>Launch URL</dt><dd>{draft.distribution.launchUrl || "-"}</dd><dt>{tr("Invitați B2B", "B2B guests")}</dt><dd>{draft.distribution.guestVisible ? tr("Vizibil", "Visible") : tr("Ascuns", "Hidden")}</dd><dt>{tr("Soluție ZIP", "Solution ZIP")}</dt><dd>{draft.distribution.downloadEnabled ? packageFile?.name ?? tr("Atașată", "Attached") : tr("Nu", "No")}</dd></dl><details className="review-configuration" open><summary>{tr("Configurație completă", "Complete configuration")}</summary><ConfigurationView draft={draft} exportable={false}/></details><Toggle label={tr("Confirm verificarea configurației, a licențelor și a permisiunilor surselor.", "I confirm the configuration, licenses and source permissions have been reviewed.")} checked={confirmed} onChange={setConfirmed}/></div>}
      </fieldset>
      <div className="form-footer"><button type="button" className="button" disabled={step === 0 || busy || uploading} onClick={() => changeStep(step - 1)}><ArrowLeft size={16}/>{tr("Înapoi", "Back")}</button><div className="row-actions">{step < 4 ? <button type="button" className="button primary" disabled={busy || uploading} onClick={locked ? () => { setVisited(Math.max(visited, step + 1)); changeStep(step + 1); } : nextStep}>{tr("Continuă", "Continue")}<ArrowRight size={16}/></button> : <button type="button" className="button primary" disabled={busy || uploading || locked || !confirmed} onClick={() => void submit()}>{busy ? <BusyIcon/> : <Send size={16}/>} {tr("Trimite spre revizuire", "Submit for review")}</button>}</div></div>
    </div></div>
  </div>;
}