"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { Archive, ArrowUpRight, Bookmark, Check, ChevronRight, Download, FileCheck2, History, LockKeyhole, Pencil, RefreshCw, Send, ShieldCheck, Undo2 } from "lucide-react";
import { api, downloadFile } from "@/lib/client";
import { riskIds, type AccessResolution, type AgentDetail, type AgentRecord } from "@/lib/contracts";
import type { RiskLevel } from "@/lib/workflow";
import { categoryName, formatDate, stateName } from "@/lib/presentation";
import { useMarketplace, useResource } from "./MarketplaceProvider";
import { useLanguage } from "./LanguageProvider";
import { AgentArtwork, Badge, BusyIcon, CopyButton, ErrorBox, Field, Loading, Modal, PlatformLabel, useText } from "./ui";
import { ConfigurationView } from "./ConfigurationView";
import { TopicList } from "./community/Discussion";
import { FollowButton } from "./community/shared";

export function ReviewControls({ record, canReview, reload }: { record: AgentRecord; canReview: boolean; reload: () => void }) {
  const { data: bootstrap, reload: reloadBootstrap } = useMarketplace(); const tr = useText(); const { locale } = useLanguage();
  const [note, setNote] = useState(""); const [risk, setRisk] = useState<RiskLevel>(record.risk); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null);
  useEffect(() => { setRisk(record.risk); setNote(""); }, [record.revision, record.risk]);
  const apply = async (action: "approve" | "request-changes" | "risk") => { setBusy(true); setError(null); try { await api(`agents/${record.id}`, { method: "PATCH", body: action === "risk" ? { action, revision: record.revision, risk } : { action, revision: record.revision, note } }); reload(); await reloadBootstrap(); } catch (failure) { setError(failure); } finally { setBusy(false); } };
  const previous = record.versions.at(-1)?.draft;
  const changed = previous ? Object.keys(record.draft).filter((key) => JSON.stringify(record.draft[key as keyof typeof record.draft]) !== JSON.stringify(previous[key as keyof typeof previous])) : [];
  const approvalsRequired = bootstrap?.settings.secondReviewer && ["High", "Critical"].includes(record.risk) ? 2 : 1;
  return <section className="review-strip"><div className="section-heading"><h2><FileCheck2 size={20}/> {tr("Revizuire", "Review")}</h2><Badge value={record.state}/></div><dl className="definition-list"><dt>{tr("Creator", "Publisher")}</dt><dd>{record.ownerName} · {record.ownerEmail}</dd><dt>{tr("Aprobări", "Approvals")}</dt><dd>{record.reviewers.length} / {approvalsRequired}</dd><dt>{tr("Revizie", "Revision")}</dt><dd>{record.revision}</dd></dl>{previous && <div className="review-diff"><strong>{tr("Câmpuri modificate față de versiunea publicată", "Fields changed since the published version")}</strong><p>{changed.join(", ") || tr("Nicio modificare", "No changes")}</p><Link target="_blank" rel="noreferrer" href={`/agents/${record.id}?version=${record.versions.at(-1)!.number}&tab=configuration`}>{tr("Deschide versiunea publicată", "Open published version")}<ArrowUpRight size={13}/></Link></div>}{record.reviewNote && <div className="decision-note"><p className="prose">{record.reviewNote}</p></div>}{Boolean(error) && <ErrorBox error={error}/>}{bootstrap?.actor?.role === "admin" && <div className="risk-control"><Field label={tr("Nivel de risc", "Risk level")}><select value={risk} disabled={busy} onChange={(event) => setRisk(event.target.value as RiskLevel)}>{riskIds.map((value) => <option key={value} value={value}>{stateName(value, locale)}</option>)}</select></Field><button className="button small" disabled={busy || risk === record.risk} onClick={() => void apply("risk")}><ShieldCheck size={15}/>{tr("Actualizează riscul", "Update risk")}</button></div>}{canReview && <><Field label={tr("Observații de revizuire", "Review notes")}><textarea rows={3} maxLength={4000} disabled={busy} value={note} onChange={(event) => setNote(event.target.value)}/></Field><div className="row-actions"><button className="button primary" disabled={busy || record.reviewers.includes(bootstrap?.actor?.id ?? "")} onClick={() => void apply("approve")}>{busy ? <BusyIcon/> : <Check size={16}/>} {tr("Aprobă revizia", "Approve revision")}</button><button className="button" disabled={busy || !note.trim()} onClick={() => void apply("request-changes")}>{tr("Solicită modificări", "Request changes")}</button></div></>}</section>;
}

function AccessPanel({ id, detail, reload }: { id: string; detail: AgentDetail; reload: () => void }) {
  const tr = useText(); const { locale } = useLanguage();
  const [access, setAccess] = useState(detail.access); const [checking, setChecking] = useState(false); const [error, setError] = useState<unknown>(null);
  const [requestOpen, setRequestOpen] = useState(false); const [justification, setJustification] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => setAccess(detail.access), [detail.access]);
  const message = detail.summary.example ? tr("Configurație de exemplu. Nu există o instanță publicată asociată.", "Example configuration. No deployed instance is linked.") : access.state === "pending" ? tr("Cererea așteaptă decizia proprietarului.", "Your request is awaiting the owner's decision.") : access.state === "approved" ? tr("Cererea este aprobată. Partajarea în Microsoft este încă în așteptare.", "Your request is approved. Sharing in Microsoft is still pending.") : access.state === "blocked" ? tr("Agent blocat în catalogul Microsoft.", "Agent blocked in the Microsoft catalog.") : access.source === "owner-confirmation" ? tr("Partajare confirmată de proprietar. Licențele și permisiunile surselor sunt verificate de Microsoft.", "Sharing confirmed by the owner. Microsoft checks licenses and source permissions.") : access.source === "microsoft-catalog" && access.state === "available" ? tr("Disponibil pentru identitatea ta în catalogul Microsoft. Licențele și permisiunile datelor se aplică separat.", "Available to your identity in the Microsoft catalog. Licensing and data permissions apply separately.") : access.source === "publisher" ? tr("Link furnizat de creator. Microsoft verifică accesul la executare.", "Link supplied by the publisher. Microsoft checks runtime access.") : access.state === "request-required" ? tr("Este necesară aprobarea proprietarului și confirmarea partajării.", "Owner approval and sharing confirmation are required.") : tr("Disponibilitatea instanței nu a fost confirmată.", "Instance availability has not been confirmed.");
  return <section className="access-panel"><div className="section-heading"><h2>{tr("Instanță publicată", "Deployed instance")}</h2><Badge value={access.state}/></div><p>{message}</p>{access.checkedAt && <small className="muted">{formatDate(access.checkedAt, locale, true)}</small>}{access.request?.note && <div className="decision-note"><strong>{access.request.updatedBy}</strong><p className="prose">{access.request.note}</p></div>}<div className="row-actions">{access.state === "available" && access.launchUrl && <a href={access.launchUrl} target="_blank" rel="noopener noreferrer" className="button primary">{tr("Deschide agentul", "Open agent")}<ArrowUpRight size={17}/></a>}{!detail.summary.example && ["request-required", "unknown"].includes(access.state) && detail.summary.requestAccess && <button className="button primary" onClick={() => { setRequestOpen(true); setError(null); }}><LockKeyhole size={16}/>{tr("Solicită acces", "Request access")}</button>}{!detail.summary.example && <button className="button" disabled={checking} onClick={async () => { setChecking(true); setError(null); try { setAccess(await api<AccessResolution>(`agents/${id}/access`)); } catch (failure) { setError(failure); } finally { setChecking(false); } }}>{checking ? <BusyIcon/> : <RefreshCw size={16}/>} {tr("Verifică disponibilitatea", "Check availability")}</button>}{access.request && <Link href="/dashboard?tab=requests" className="subtle-link">{tr("Urmărește cererea", "Track request")}</Link>}</div>{Boolean(error) && !requestOpen && <ErrorBox error={error}/>}<small className="muted">{tr("Accesul la configurație nu acordă acces la datele sau instanța agentului.", "Configuration access does not grant access to the agent's data or deployed instance.")}</small>
      {requestOpen && <Modal title={tr("Solicită acces", "Request access")} close={() => { if (!busy) setRequestOpen(false); }}><h3>{detail.summary.name}</h3>{Boolean(error) && <ErrorBox error={error}/>}<Field label={tr("Justificare de business", "Business justification")} required hint={tr("Minimum 10 caractere", "At least 10 characters")}><textarea autoFocus rows={5} minLength={10} maxLength={4000} value={justification} onChange={(event) => setJustification(event.target.value)} disabled={busy}/></Field><div className="row-actions"><button className="button" disabled={busy} onClick={() => setRequestOpen(false)}>{tr("Renunță", "Dismiss")}</button><button className="button primary" disabled={busy || justification.trim().length < 10} onClick={async () => { setBusy(true); setError(null); try { await api(`agents/${id}/requests`, { method: "POST", body: { justification } }); setRequestOpen(false); setJustification(""); reload(); } catch (failure) { setError(failure); } finally { setBusy(false); } }}>{busy ? <BusyIcon/> : <Send size={16}/>}{tr("Trimite cererea", "Send request")}</button></div></Modal>}
    </section>;
}

export function AgentDetailView({ id }: { id: string }) {
  const params = useSearchParams(); const draftView = params.get("draft") === "true"; const version = params.get("version");
  const resource = useResource<AgentDetail>(`agents/${encodeURIComponent(id)}?${draftView ? "draft=true" : version ? `version=${encodeURIComponent(version)}` : ""}`);
  const { data: bootstrap, reload: reloadBootstrap } = useMarketplace(); const { locale } = useLanguage(); const tr = useText();
  const communityEnabled = Boolean(resource.data?.community?.enabled && !draftView);
  const selectedTab = params.get("tab") ?? "overview";
  const tab = ["overview", "configuration", "distribution", "versions", ...(communityEnabled ? ["community"] : [])].includes(selectedTab) ? selectedTab : "overview";
  const setTab = (key: string) => {
    const url = new URL(window.location.href);
    url.searchParams.set("tab", key);
    window.history.replaceState(null, "", url);
  };
  const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null); const [confirmAction, setConfirmAction] = useState<"archive" | "restore" | null>(null);
  const refresh = () => { resource.reload(); void reloadBootstrap(); };
  if (resource.loading) return <div className="page-width page-content"><Loading rows={5}/></div>;
  if (resource.error || !resource.data) return <div className="page-width page-content"><ErrorBox error={resource.error ?? tr("Agentul nu a fost găsit.", "Agent not found.")} retry={resource.reload}/><Link href="/">{tr("Înapoi la catalog", "Back to catalog")}</Link></div>;
  const detail = resource.data; const record = detail.record; const summary = detail.summary;
  const showReview = Boolean(draftView && record && (detail.canReview || bootstrap?.actor?.role === "admin" || record.state === "in-review" || record.state === "changes-requested"));
  const action = async () => { if (!record || !confirmAction) return; setBusy(true); setError(null); try { await api<AgentRecord>(`agents/${id}`, { method: "PATCH", body: { action: confirmAction, revision: record.revision } }); setConfirmAction(null); refresh(); } catch (failure) { setError(failure); } finally { setBusy(false); } };
  return <div className="page-width page-content"><div className="breadcrumbs"><Link href="/">{tr("Catalog", "Catalog")}</Link><ChevronRight size={13}/><Link href={`/?category=${summary.category}`}>{categoryName(summary.category, locale)}</Link><ChevronRight size={13}/><span>{summary.name}</span></div>
    <div className="agent-detail-heading"><AgentArtwork iconId={summary.iconId} platform={summary.platform} large/><div className="agent-title"><PlatformLabel platform={summary.platform}/><h1>{summary.name}</h1><p>{summary.summary}</p><div className="detail-byline">{detail.community?.ownerProfileId ? <Link href={`/community/people/${encodeURIComponent(detail.community.ownerProfileId)}`}>{summary.ownerName}</Link> : <span>{summary.ownerName}</span>}<span>{draftView ? `${tr("Ciornă", "Draft")} · r${record?.revision}` : `v${summary.version}`}</span><Badge value={summary.risk}/>{summary.example && <span className="example-label">{tr("Exemplu", "Example")}</span>}</div></div><div className="detail-heading-actions">{communityEnabled && <FollowButton target={{ kind: "agent", id }}/>} {detail.canEdit && <Link className="button" href={`/submit?id=${id}`}><Pencil size={16}/>{tr("Editează", "Edit")}</Link>}{!draftView && summary.state !== "archived" && <button className="icon-button" title={summary.saved ? tr("Elimină din salvate", "Remove from saved") : tr("Salvează agentul", "Save agent")} aria-label={summary.saved ? tr("Elimină din salvate", "Remove from saved") : tr("Salvează agentul", "Save agent")} aria-pressed={summary.saved} disabled={busy} onClick={async () => { setBusy(true); setError(null); try { await api(`agents/${id}/favorite`, { method: "PUT", body: { saved: !summary.saved } }); resource.setData({ ...detail, summary: { ...summary, saved: !summary.saved } }); } catch (failure) { setError(failure); } finally { setBusy(false); } }}><Bookmark size={19} fill={summary.saved ? "currentColor" : "none"}/></button>}{record && (detail.canEdit || bootstrap?.actor?.role === "admin") && <button className="icon-button" title={record.state === "archived" ? tr("Restaurează", "Restore") : tr("Arhivează", "Archive")} aria-label={record.state === "archived" ? tr("Restaurează", "Restore") : tr("Arhivează", "Archive")} onClick={() => { setError(null); setConfirmAction(record.state === "archived" ? "restore" : "archive"); }}>{record.state === "archived" ? <Undo2 size={18}/> : <Archive size={18}/>}</button>}</div></div>
    {Boolean(error) && !confirmAction && <ErrorBox error={error}/>} {draftView && <div className="info-notice"><FileCheck2 size={17}/><span>{tr("Ciornă de lucru", "Working draft")} · <Badge value={record?.state ?? "draft"}/></span>{summary.version > 0 && <Link href={`/agents/${id}`}>{tr("Versiunea publicată", "Published version")}</Link>}</div>}{version && <div className="info-notice"><History size={17}/><span>{tr("Versiune istorică", "Historical version")} {version}</span><Link href={`/agents/${id}`}>{tr("Ultima versiune", "Latest version")}</Link></div>}
    <div className="tabs" role="tablist" aria-label={tr("Fișa agentului", "Agent details")}>{[["overview", tr("Prezentare", "Overview")], ["configuration", tr("Configurație", "Configuration")], ["distribution", tr("Acces și import", "Access and import")], ...(communityEnabled ? [["community", tr("Întrebări și discuții", "Questions and discussions")]] : []), ["versions", tr("Versiuni", "Versions")]].map(([key, label]) => <button key={key} role="tab" aria-selected={tab === key} aria-controls="agent-tab-panel" id={`tab-${key}`} onClick={() => setTab(key)}>{label}</button>)}</div>
    <div className={`detail-layout ${showReview ? "with-review" : ""}`}><div role="tabpanel" id="agent-tab-panel" aria-labelledby={`tab-${tab}`} className="detail-main">
    {tab === "community" && <TopicList kind="discussion" agentId={id} allowGuests={detail.community?.guestVisible}/>}
    {tab === "overview" && <><section className="section-block"><h2>{tr("Despre agent", "About this agent")}</h2><p className="prose">{detail.overview || detail.summary.summary}</p></section><section className="section-block"><h3>{tr("Licențe și condiții de utilizare", "Licensing and usage requirements")}</h3><p className="prose">{detail.license || tr("Nespecificat", "Not provided")}</p></section><section className="section-block"><h3>{tr("Limitări și riscuri cunoscute", "Known limitations and risks")}</h3><p className="prose">{detail.limitations || tr("Nedeclarate de creator", "Not declared by the publisher")}</p></section><section className="section-block"><dl className="definition-list"><dt>{tr("Platformă", "Platform")}</dt><dd><PlatformLabel platform={summary.platform}/></dd><dt>{tr("Categorie", "Category")}</dt><dd>{categoryName(summary.category, locale)}</dd><dt>{tr("Limba agentului", "Agent language")}</dt><dd>{detail.language || "-"}</dd><dt>{tr("Actualizat", "Updated")}</dt><dd>{formatDate(summary.updatedAt, locale, true)}</dd><dt>Tags</dt><dd><div className="tag-list">{summary.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></dd></dl></section>{detail.configuration?.prompts.length ? <section className="section-block"><h3>Starter prompts</h3><div className="prompt-list">{detail.configuration.prompts.map((prompt, index) => <div className="readout" key={index}><div className="readout-header"><h3>{prompt.title}</h3><CopyButton value={prompt.message} label={`${tr("Copiază", "Copy")} ${prompt.title}`}/></div><p className="prose">{prompt.message}</p></div>)}</div></section> : null}<AccessPanel id={id} detail={detail} reload={refresh}/></>}
    {tab === "configuration" && (detail.configuration ? <ConfigurationView draft={detail.configuration}/> : <div className="info-notice"><LockKeyhole size={20}/>{tr("Configurația este disponibilă doar membrilor interni autorizați.", "Configuration is available to authorized internal members only.")}</div>)}
    {tab === "distribution" && <><AccessPanel id={id} detail={detail} reload={refresh}/><section className="section-block"><h2>{summary.platform === "copilot-studio" ? tr("Import într-un alt mediu", "Import into another environment") : tr("Reproducere în Agent Builder", "Reproduce in Agent Builder")}</h2>{summary.platform === "copilot-studio" ? detail.file ? <div className="form-stack"><dl className="definition-list"><dt>{tr("Pachet", "Package")}</dt><dd>{detail.file.name}</dd><dt>{tr("Dimensiune", "Size")}</dt><dd>{(detail.file.bytes / 1024 / 1024).toLocaleString(locale, { maximumFractionDigits: 2 })} MB</dd><dt>Solution</dt><dd>{detail.file.solution?.uniqueName}</dd><dt>Version</dt><dd>{detail.file.solution?.version} · {detail.file.solution?.managed ? "Managed" : "Unmanaged"}</dd><dt>SHA-256</dt><dd><code>{detail.file.sha256}</code><CopyButton value={detail.file.sha256} label="Copy SHA-256"/></dd></dl><div className="row-actions"><button className="button primary" disabled={busy || !bootstrap?.settings.downloadsEnabled || (!summary.downloadable && !draftView)} onClick={async () => { setBusy(true); setError(null); try { await downloadFile(detail.file!.id, detail.file!.name); } catch (failure) { setError(failure); } finally { setBusy(false); } }}>{busy ? <BusyIcon/> : <Download size={16}/>}{tr("Descarcă soluția ZIP", "Download solution ZIP")}</button><a className="button" target="_blank" rel="noopener noreferrer" href="https://make.powerapps.com/">Power Apps<ArrowUpRight size={15}/></a></div>{!bootstrap?.settings.downloadsEnabled && <div className="info-notice">{tr("Descărcările sunt dezactivate prin politică.", "Downloads are disabled by policy.")}</div>}<Link href="/resources#studio-import" className="subtle-link">{tr("Cerințe și pași de import", "Import requirements and steps")}<ArrowUpRight size={14}/></Link></div> : <p className="muted">{tr("Nicio soluție ZIP accesibilă. Un ZIP de aplicație Teams sau Agent Builder nu este o soluție Power Platform.", "No accessible solution ZIP. A Teams app or Agent Builder ZIP is not a Power Platform solution.")}</p> : <div className="form-stack"><p>{tr("Agent Builder nu folosește soluții Power Platform. Configurația publicată este disponibilă în fila Configurație, conform politicii de acces.", "Agent Builder does not use Power Platform solutions. Published settings are available in the Configuration tab, subject to access policy.")}</p><Link href="/resources#agent-builder" className="subtle-link">{tr("Documentație Agent Builder", "Agent Builder documentation")}<ArrowUpRight size={14}/></Link></div>}</section></>}
    {tab === "versions" && <section className="version-list">{detail.versions.length ? [...detail.versions].reverse().map((entry) => <article key={entry.number}><div className="version-marker"><History size={18}/></div><div><h3><Link href={`/agents/${id}?version=${entry.number}`}>{tr("Versiunea", "Version")} {entry.number}</Link></h3><time dateTime={entry.publishedAt}>{formatDate(entry.publishedAt, locale, true)}</time><p className="prose">{entry.releaseNotes || tr("Fără note de versiune", "No release notes")}</p></div></article>) : <p className="muted">{tr("Nicio versiune publicată", "No published versions")}</p>}</section>}
    </div>{showReview && record && <aside><ReviewControls record={record} canReview={detail.canReview} reload={refresh}/></aside>}</div>
    {confirmAction && <Modal title={confirmAction === "archive" ? tr("Arhivează agentul", "Archive agent") : tr("Restaurează agentul", "Restore agent")} close={() => { if (!busy) setConfirmAction(null); }}><p>{confirmAction === "archive" ? tr("Agentul și versiunile sale nu vor mai fi vizibile în catalog. Deploymentul Microsoft nu este șters.", "The agent and its versions will no longer be visible in the catalog. The Microsoft deployment is not deleted.") : tr("Agentul revine în stare de ciornă. Dacă are o versiune publicată, aceasta redevine vizibilă în catalog.", "The agent returns to draft. Any previously published version becomes visible in the catalog again.")}</p>{Boolean(error) && <ErrorBox error={error}/>}<div className="row-actions"><button className="button" disabled={busy} onClick={() => setConfirmAction(null)}>{tr("Renunță", "Dismiss")}</button><button className="button primary" disabled={busy} onClick={() => void action()}>{busy ? <BusyIcon/> : <Check size={16}/>}{tr("Confirmă", "Confirm")}</button></div></Modal>}
  </div>;
}